//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEmoPrac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activnost_meropriyatie
    {
        public int ID { get; set; }
        public Nullable<int> ID_activnosti { get; set; }
        public Nullable<int> ID_meropriyatiya { get; set; }
        public Nullable<int> Den_provedeniya { get; set; }
        public Nullable<System.TimeSpan> Vremya_nachala { get; set; }
        public Nullable<int> ID_polzovatelya_moderator { get; set; }
    
        public virtual Activnosti Activnosti { get; set; }
        public virtual Meropriatiya Meropriatiya { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
    }
}
