//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEmoPrac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorod_meropriyatiye
    {
        public int ID_gorod_merop { get; set; }
        public int ID_meropriyatiya { get; set; }
        public int ID_goroda { get; set; }
    
        public virtual Goroda Goroda { get; set; }
        public virtual Meropriatiya Meropriatiya { get; set; }
    }
}
