//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEmoPrac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriatiya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meropriatiya()
        {
            this.Activnost_meropriyatie = new HashSet<Activnost_meropriyatie>();
            this.Gorod_meropriyatiye = new HashSet<Gorod_meropriyatiye>();
            this.Meropriyatie_juri = new HashSet<Meropriyatie_juri>();
            this.Meropriyatiye_tip_Meropriyatiya_napravleniye = new HashSet<Meropriyatiye_tip_Meropriyatiya_napravleniye>();
            this.Polzovateli_meropriatiya = new HashSet<Polzovateli_meropriatiya>();
        }
    
        public int ID_meropriatia { get; set; }
        public string Naimenovanie { get; set; }
        public Nullable<System.DateTime> Date_nachala { get; set; }
        public Nullable<int> Colvo_dney { get; set; }
        public Nullable<int> ID_polzovatelya { get; set; }
        public string ImagePho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activnost_meropriyatie> Activnost_meropriyatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorod_meropriyatiye> Gorod_meropriyatiye { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meropriyatie_juri> Meropriyatie_juri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meropriyatiye_tip_Meropriyatiya_napravleniye> Meropriyatiye_tip_Meropriyatiya_napravleniye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovateli_meropriatiya> Polzovateli_meropriatiya { get; set; }
    }
}
