//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEmoPrac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriyatie_juri
    {
        public int ID_meropriyatiya { get; set; }
        public int ID_activnosti { get; set; }
        public int ID_polzovatelya_juri { get; set; }
    
        public virtual Activnosti Activnosti { get; set; }
        public virtual Meropriatiya Meropriatiya { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
    }
}
