//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEmoPrac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriyatiye_tip_Meropriyatiya_napravleniye
    {
        public int ID_meropriatiya { get; set; }
        public int ID_tip_meropriyatiya { get; set; }
        public int ID_napravleniya { get; set; }
    
        public virtual Meropriatiya Meropriatiya { get; set; }
        public virtual Napravleniya Napravleniya { get; set; }
        public virtual Tipi_meropriatiya Tipi_meropriatiya { get; set; }
    }
}
