//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEmoPrac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polzovateli()
        {
            this.Activnost_meropriyatie = new HashSet<Activnost_meropriyatie>();
            this.Meropriatiya = new HashSet<Meropriatiya>();
            this.Meropriyatie_juri = new HashSet<Meropriyatie_juri>();
            this.Polzovatel_napravlenie = new HashSet<Polzovatel_napravlenie>();
            this.Polzovatel_pol = new HashSet<Polzovatel_pol>();
            this.Polzovatel_role = new HashSet<Polzovatel_role>();
            this.Polzovateli_meropriatiya = new HashSet<Polzovateli_meropriatiya>();
        }
    
        public int ID { get; set; }
        public string Phamilia { get; set; }
        public string Ima { get; set; }
        public string Otchestvo { get; set; }
        public string Pochta { get; set; }
        public Nullable<System.DateTime> Data_rozhdenia { get; set; }
        public string Telephone { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
        public Nullable<int> ID_strani { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activnost_meropriyatie> Activnost_meropriyatie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meropriatiya> Meropriatiya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meropriyatie_juri> Meropriyatie_juri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovatel_napravlenie> Polzovatel_napravlenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovatel_pol> Polzovatel_pol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovatel_role> Polzovatel_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polzovateli_meropriatiya> Polzovateli_meropriatiya { get; set; }
        public virtual Strani Strani { get; set; }
    }
}
