//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEmoPrac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polzovateli_meropriatiya
    {
        public int ID_polzovatel_meropriyatia { get; set; }
        public int ID_polzovatelya { get; set; }
        public int ID_meropriatia { get; set; }
    
        public virtual Meropriatiya Meropriatiya { get; set; }
        public virtual Polzovateli Polzovateli { get; set; }
    }
}
